#!/usr/bin/env node
/**
 * Scoxton — Research Runner
 * Usage: node scoxton-run.js "Research [target]" [output_dir]
 * 
 * Spawned by Axton as a sub-agent task.
 */

const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');

const TASK = process.argv[2] || 'Research the top 10 co-working spaces in Madrid, find owner/manager names and email addresses';
const OUTPUT_DIR = process.argv[3] || 'research';
const DATE = new Date().toISOString().split('T')[0];
const FELO_KEY = process.env.FELO_KEY || '';
const SCRAPE_KEY = process.env.SCRAPE_KEY || '';

const colors = {
  reset: '\x1b[0m',
  cyan: '\x1b[36m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m'
};

function log(color, prefix, msg) {
  console.log(`${color}[${prefix}]${colors.reset} ${msg}`);
}

function saveOutput(filename, content) {
  const dir = path.join(process.cwd(), OUTPUT_DIR);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const filepath = path.join(dir, filename);
  fs.writeFileSync(filepath, content);
  log(colors.green, 'SAVED', filepath);
  return filepath;
}

async function webSearch(query) {
  log(colors.cyan, 'SEARCH', query);
  try {
    const resp = await fetch('https://openapi.felo.ai/v2/chat', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${FELO_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ query })
    });
    const data = await resp.json();
    return data.data?.answer || '';
  } catch (e) {
    log(colors.red, 'ERROR', e.message);
    return '';
  }
}

async function main() {
  console.log(`\n${colors.cyan}══════════════════════════════════════`);
  console.log(`  SCOXTON — Research Agent`);
  console.log(`  Task: ${TASK}`);
  console.log(`═══════════════════════════════════════${colors.reset}\n`);
  
  // Step 1: Web research via Felo
  log(colors.yellow, 'SCOXTON', 'Starting research...');
  
  const findings = await webSearch(TASK + '. Provide specific names, titles, emails if available.');
  
  // Step 2: Save findings
  const output = `# Research — ${TASK}
Date: ${DATE}
Agent: Scoxton

## Task
${TASK}

## Findings
${findings || 'No findings returned.'}

## Next Steps
- Verify contact info manually
- Cross-reference with LinkedIn
- Pass to Haxton for outreach sequence

---
_Generated by Scoxton — Axton's research agent_
`;
  
  const filename = `${DATE}-scoxton-research.md`;
  saveOutput(filename, output);
  
  console.log(`\n${colors.green}══════════════════════════════════════`);
  console.log(`  SCOXTON — Research Complete`);
  console.log(`═══════════════════════════════════════${colors.reset}\n`);
}

main().catch(e => {
  log(colors.red, 'FATAL', e.message);
  process.exit(1);
});
