#!/bin/bash
# Contract Generator
# Generate service agreements for deals

set -e

CONTRACTS_DIR="/data/workspace/PROJECTS"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[CONTRACT]${NC} $1"; }
success() { echo -e "${GREEN}[CONTRACT]${NC} $1"; }
error() { echo -e "${RED}[CONTRACT]${NC} $1"; }

# Generate contract
generate_contract() {
    local project="$1"
    local client="$2"
    local terms="$3"
    local start_date="${4:-$(date +%Y-%m-%d)}"
    local end_date="${5:-}"
    local value="$6"
    
    if [[ -z "$project" || -z "$client" || -z "$terms" ]]; then
        error "Usage: generate-contract <project> <client> <terms> [start] [end] [value]"
        return 1
    fi
    
    mkdir -p "$CONTRACTS_DIR/$project/contracts"
    
    local contract_num=$(date +%Y%m%d%H%M%S)
    local output_file="$CONTRACTS_DIR/$project/contracts/CONTRACT-${contract_num}.md"
    local date=$(date +%Y-%m-%d)
    
    # Get project-specific content
    case "$project" in
        pisco)
            local service_type="Staff Placement Agreement"
            local default_terms="This agreement covers the placement of Filipino professionals. Placement fee is equivalent to one month's salary. 6-month guarantee period."
            ;;
        comare)
            local service_type="Maintenance Services Agreement"
            local default_terms="Monthly maintenance services for pharmacy. Billed monthly in advance. 30-day cancellation notice required."
            ;;
        *)
            local service_type="Services Agreement"
            local default_terms="Professional services as discussed and agreed."
            ;;
    esac
    
    terms=${terms:-$default_terms}
    
    cat > "$output_file" << EOF
# SERVICES AGREEMENT

---

**Agreement Number:** CONTRACT-$contract_num  
**Date:** $date  
**Effective Date:** $start_date
${end_date:+
**End Date:** $end_date}

---

## PARTIES

**Service Provider:**  
Jordan Hays  
[Address]  
[Email]  
[Phone]

**Client:**  
$client

---

## SERVICE DESCRIPTION

**Type:** $service_type

$terms

---

## COMPENSATION

${value:+**Total Value:** €$value}

Payment terms as agreed separately.

---

## TERM AND TERMINATION

**Term:**  
This agreement begins on $start_date ${end_date:+and ends on $end_date} and continues month-to-month thereafter.

**Termination:**  
Either party may terminate with 30 days written notice.

---

## RESPONSIBILITIES

**Service Provider agrees to:**
- Provide professional services as described
- Maintain appropriate qualifications
- Communicate regularly with client
- Address concerns promptly

**Client agrees to:**
- Provide necessary information and access
- Make timely payments
- Communicate needs clearly

---

## CONFIDENTIALITY

Both parties agree to maintain confidentiality of proprietary information shared during the engagement.

---

## LIMITATION OF LIABILITY

Service Provider's liability is limited to the amount paid under this agreement.

---

## GOVERNING LAW

This agreement is governed by the laws of Spain.

---

## SIGNATURES

By signing below, both parties agree to these terms.

**Service Provider:**  
Name: Jordan Hays  
Signature: _______________________  
Date: $date

**Client:**  
Name: _______________________  
Signature: _______________________  
Date: _______________

---

*⚠️ REVIEW BEFORE SIGNING — This is a template only*  
*Consult a legal professional before finalizing*

---
*Generated by Jordan's Revenue System*
EOF
    
    success "Contract generated: $output_file"
    echo ""
    echo "📄 Contract created: $output_file"
    echo "👤 Client: $client"
    echo "📅 Effective: $start_date"
    ${value:+echo "💰 Value: €$value"}
    echo ""
    echo "⚠️ IMPORTANT: Have legal review before signing"
    echo ""
    
    # Log to contract tracker
    log_contract "$project" "$contract_num" "$client" "$date" "$value"
    
    echo "$output_file"
}

# Log contract
log_contract() {
    local project="$1"
    local contract_num="$2"
    local client="$3"
    local date="$4"
    local value="${5:-TBD}"
    
    local tracker="$CONTRACTS_DIR/$project/contracts/log.md"
    mkdir -p "$CONTRACTS_DIR/$project/contracts"
    
    if [[ ! -f "$tracker" ]]; then
        cat > "$tracker" << 'EOF'
# Contract Log

| Contract # | Client | Date | Value | Status | Signed Date |
|------------|--------|------|-------|--------|-------------|
EOF
    fi
    
    cat >> "$tracker" << EOF
| CONTRACT-$contract_num | $client | $date | €$value | PENDING | - |
EOF
}

# Mark as signed
mark_signed() {
    local project="$1"
    local contract_num="$2"
    local signed_date="${3:-$(date +%Y-%m-%d)}"
    
    if [[ -z "$project" || -z "$contract_num" ]]; then
        error "Usage: mark-signed <project> <contract_num> [date]"
        return 1
    fi
    
    local tracker="$CONTRACTS_DIR/$project/contracts/log.md"
    
    if [[ ! -f "$tracker" ]]; then
        error "No contract log found for $project"
        return 1
    fi
    
    sed -i "s/| CONTRACT-$contract_num |/| CONTRACT-$contract_num */" "$tracker"
    sed -i "s/| PENDING |/| SIGNED |/" "$tracker"
    sed -i "s/| - |$/| $signed_date |/" "$tracker"
    
    success "Contract CONTRACT-$contract_num marked as SIGNED on $signed_date"
}

# Mark as renegotiated
mark_renegotiated() {
    local project="$1"
    local contract_num="$2"
    
    if [[ -z "$project" || -z "$contract_num" ]]; then
        error "Usage: mark-renegotiated <project> <contract_num>"
        return 1
    fi
    
    local tracker="$CONTRACTS_DIR/$project/contracts/log.md"
    sed -i "s/| PENDING |/| RENEGOTIATING |/" "$tracker"
    success "Contract CONTRACT-$contract_num marked as RENEGOTIATING"
}

# List contracts
list_contracts() {
    local project="${1:-}"
    
    echo ""
    echo "═══════════════════════════════════════════"
    echo "  CONTRACT TRACKER"
    echo "═══════════════════════════════════════════"
    echo ""
    
    if [[ -n "$project" ]]; then
        local tracker="$CONTRACTS_DIR/$project/contracts/log.md"
        if [[ -f "$tracker" ]]; then
            echo "📁 $project:"
            cat "$tracker"
        else
            echo "  No contracts for $project"
        fi
    else
        find "$CONTRACTS_DIR" -name "log.md" -exec grep -l "CONTRACT-" {} \; 2>/dev/null | while read log; do
            local proj=$(echo "$log" | cut -d'/' -f6)
            local pending=$(grep -c "PENDING" "$log" 2>/dev/null || echo "0")
            local signed=$(grep -c "SIGNED" "$log" 2>/dev/null || echo "0")
            echo "📁 $proj: $pending pending, $signed signed"
        done
    fi
    
    echo ""
}

# Main
case "${1:-help}" in
    generate)
        generate_contract "$2" "$3" "$4" "$5" "$6" "$7"
        ;;
    signed)
        mark_signed "$2" "$3" "$4"
        ;;
    renegotiated)
        mark_renegotiated "$2" "$3"
        ;;
    list)
        list_contracts "$2"
        ;;
    help)
        echo "Contract Generator"
        echo ""
        echo "Usage: contract_generator.sh <command> [args]"
        echo ""
        echo "Commands:"
        echo "  generate <proj> <client> <terms> [start] [end] [value]"
        echo "                                  Create new contract"
        echo "  signed <project> <num> [date]  Mark as signed"
        echo "  renegotiated <project> <num>    Mark for renegotiation"
        echo "  list [project]                   List contracts"
        ;;
esac
