#!/bin/bash
# git_monitor.sh — Monitor git commits across all projects
# Usage: ./git_monitor.sh [since_days=1]
# Cron: 0 9 * * * /data/workspace/tools/git_monitor.sh >> /data/workspace/logs/git-monitor.log 2>&1

set -e
SINCE_DAYS="${1:-1}"
DATE=$(date '+%Y-%m-%d')
PROJECTS_DIR="/data/workspace"
PROJECTS=("PISCO" "COMARE" "Dealsmap" "PISCO-main" "comare-main" "dealsmap-main" "PROJECTS")

echo "📊 Git Monitor — Last $SINCE_DAYS day(s)"
echo ""

# Find all git repos
find_git_repos() {
    find "$PROJECTS_DIR" -name ".git" -type d 2>/dev/null | while read gitdir; do
        dirname "$gitdir"
    done
}

# Parse commit info
parse_commits() {
    local repo="$1"
    local since_date=$(date -d "$SINCE_DAYS days ago" '+%Y-%m-%d')
    
    if [[ ! -d "$repo/.git" ]]; then
        return
    fi
    
    # Get project name
    PROJECT=$(basename "$repo")
    
    # Get commits since date
    cd "$repo"
    COMMITS=$(git log --since="$since_date" --pretty=format:"%h|%s|%an|%ad" --date=short 2>/dev/null || echo "")
    
    if [[ -n "$COMMITS" ]]; then
        echo "### $PROJECT ($repo)"
        echo ""
        while IFS='|' read -r hash subject author date; do
            [[ -z "$hash" ]] && continue
            echo "- \`$hash\` **$subject** — $author ($date)"
        done <<< "$COMMITS"
        echo ""
    fi
}

# Build summary
build_summary() {
    local output="/data/workspace/PROJECTS/git-summary-$DATE.md"
    
    echo "# Git Activity Summary — $DATE" > "$output"
    echo "" >> "$output"
    echo "Period: Last $SINCE_DAYS day(s)" >> "$output"
    echo "" >> "$output"
    
    TOTAL=0
    
    for repo in $(find_git_repos); do
        PROJECT=$(basename "$repo")
        COUNT=$(cd "$repo" && git log --since="$SINCE_DAYS days ago" --oneline 2>/dev/null | wc -l || echo "0")
        TOTAL=$((TOTAL + COUNT))
        
        if [[ "$COUNT" -gt 0 ]]; then
            # Check if project matches known projects
            AFFECTED=""
            for known in "${PROJECTS[@]}"; do
                if [[ "$PROJECT" == *"$known"* ]]; then
                    AFFECTED="$AFFECTED $known"
                fi
            done
            
            echo "- **$PROJECT**: $COUNT commits$AFFECTED" >> "$output"
            
            # Detailed commits
            echo "" >> "$output"
            echo "  \`\`\`" >> "$output"
            cd "$repo" && git log --since="$SINCE_DAYS days ago" --pretty="  %h %s" 2>/dev/null >> "$output" || true
            echo "  \`\`\`" >> "$output"
            echo "" >> "$output"
        fi
    done
    
    echo "---" >> "$output"
    echo "" >> "$output"
    echo "**Total commits: $TOTAL**" >> "$output"
    echo "" >> "$output"
    
    # Auto standup format
    echo "## 🤖 Auto-Standup for Jordan" >> "$output"
    echo "" >> "$output"
    echo "\`\`\`" >> "$output"
    echo "Yesterday: $TOTAL commits across projects" >> "$output"
    echo "" >> "$output"
    for known in PISCO COMARE Dealsmap; do
        for repo in $(find_git_repos); do
            if [[ "$repo" == *"$known"* ]]; then
                COUNT=$(cd "$repo" && git log --since="$SINCE_DAYS days ago" --oneline 2>/dev/null | wc -l || echo "0")
                echo "- $known: $COUNT commits" >> "$output"
            fi
        done
    done
    echo "\`\`\`" >> "$output"
    
    echo "$output"
}

# Generate link between commits and events
link_commits_to_events() {
    local output="/data/workspace/PROJECTS/git-events-$DATE.md"
    
    echo "# Git → Events Link — $DATE" > "$output"
    echo "" >> "$output"
    
    # Search commit messages for keywords that match known events
    for repo in $(find_git_repos); do
        PROJECT=$(basename "$repo")
        cd "$repo"
        
        git log --since="$SINCE_DAYS days ago" --pretty=format:"%h|%s" 2>/dev/null | while IFS='|' read -r hash subject; do
            [[ -z "$hash" ]] && continue
            
            # Link to deals/events based on keywords
            case "$subject" in
                *deal*|*client*|*revenue*) echo "- $PROJECT: $hash — **DEAL** \"$subject\"" >> "$output" ;;
                *fix*|*bug*|*hotfix*) echo "- $PROJECT: $hash — **FIX** \"$subject\"" >> "$output" ;;
                *feature*|*launch*) echo "- $PROJECT: $hash — **FEATURE** \"$subject\"" >> "$output" ;;
                *lead*|*prospect*) echo "- $PROJECT: $hash — **LEAD** \"$subject\"" >> "$output" ;;
            esac
        done
    done
    
    echo "" >> "$output"
    echo "*Generated by Axton's Git Monitor*" >> "$output"
    
    echo "$output"
}

# Run
OUTPUT1=$(build_summary)
OUTPUT2=$(link_commits_to_events)

echo "✅ Summary saved: $OUTPUT1"
echo "✅ Events linked: $OUTPUT2"
echo ""
cat "$OUTPUT1"
