#!/bin/bash
# Invoice Generator
# Generate professional invoices when deals close

set -e

INVOICES_DIR="/data/workspace/PROJECTS"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[INVOICE]${NC} $1"; }
success() { echo -e "${GREEN}[INVOICE]${NC} $1"; }
error() { echo -e "${RED}[INVOICE]${NC} $1"; }

# Invoice template
generate_invoice() {
    local project="$1"
    local client="$2"
    local amount="$3"
    local description="${4:-Professional services}"
    local invoice_num="${5:-$(date +%Y%m%d%H%M%S)}"
    
    if [[ -z "$project" || -z "$client" || -z "$amount" ]]; then
        error "Usage: generate-invoice <project> <client> <amount> [description] [invoice_num]"
        return 1
    fi
    
    # Create project invoices dir
    mkdir -p "$INVOICES_DIR/$project/invoices"
    
    local output_file="$INVOICES_DIR/$project/invoices/INV-${invoice_num}.md"
    local date=$(date +%Y-%m-%d)
    local due_date=$(date -d "+30 days" +%Y-%m-%d)
    
    cat > "$output_file" << EOF
# INVOICE

![Company Logo]

## Invoice Details
| | |
|---|---|
| **Invoice #** | INV-$invoice_num |
| **Date** | $date |
| **Due Date** | $due_date |
| **Status** | UNPAID |

---

## Bill To
**$client**

---

## Description

| Item | Amount |
|------|--------|
| $description | €$amount |
| | |
| **TOTAL DUE** | **€$amount** |

---

## Payment Terms
- Payment due within 30 days
- Bank transfer preferred
- Include invoice number in payment reference

## Bank Details
- Bank: [BANK NAME]
- Account: [ACCOUNT NUMBER]
- IBAN: [IBAN]
- BIC/SWIFT: [BIC]

---

## Notes
Thank you for your business!

---
*Generated by Jordan's Revenue System*
EOF
    
    success "Invoice generated: $output_file"
    echo ""
    echo "📄 Invoice created: $output_file"
    echo "💰 Amount: €$amount"
    echo "📅 Due: $due_date"
    echo ""
    
    # Log to invoice tracker
    log_invoice "$project" "$invoice_num" "$client" "$amount" "$date" "$due_date"
    
    echo "$output_file"
}

# Invoice tracker
log_invoice() {
    local project="$1"
    local inv_num="$2"
    local client="$3"
    local amount="$4"
    local date="$5"
    local due="$6"
    
    local tracker="$INVOICES_DIR/$project/invoices/log.md"
    
    mkdir -p "$INVOICES_DIR/$project/invoices"
    
    if [[ ! -f "$tracker" ]]; then
        cat > "$tracker" << 'EOF'
# Invoice Log

| Invoice # | Client | Amount | Date | Due | Status | Paid Date |
|-----------|--------|--------|------|-----|--------|-----------|
EOF
    fi
    
    cat >> "$tracker" << EOF
| INV-$inv_num | $client | €$amount | $date | $due | UNPAID | - |
EOF
}

# Mark as paid
mark_paid() {
    local project="$1"
    local inv_num="$2"
    local paid_date="${3:-$(date +%Y-%m-%d)}"
    
    if [[ -z "$project" || -z "$inv_num" ]]; then
        error "Usage: mark-paid <project> <invoice_num> [paid_date]"
        return 1
    fi
    
    local tracker="$INVOICES_DIR/$project/invoices/log.md"
    
    if [[ ! -f "$tracker" ]]; then
        error "No invoice log found for $project"
        return 1
    fi
    
    sed -i "s/| INV-$inv_num |/| INV-$inv_num */" "$tracker"
    sed -i "s/| UNPAID |/|$paid_date |/" "$tracker"
    sed -i "s/| - |$/| PAID |/" "$tracker"
    
    success "Invoice INV-$inv_num marked as PAID on $paid_date"
}

# List unpaid invoices
list_unpaid() {
    echo ""
    echo "═══════════════════════════════════════════"
    echo "  UNPAID INVOICES"
    echo "═══════════════════════════════════════════"
    echo ""
    
    find "$INVOICES_DIR" -name "log.md" -exec grep -l "UNPAID" {} \; 2>/dev/null | while read log; do
        local project=$(echo "$log" | cut -d'/' -f6)
        echo "📁 $project:"
        grep "UNPAID" "$log" | while read line; do
            echo "  $line"
        done
    done
    
    if [[ $(find "$INVOICES_DIR" -name "log.md" -exec grep -c "UNPAID" {} \; 2>/dev/null | grep -v "^0$" | wc -l) -eq 0 ]]; then
        echo "  ✅ All invoices paid!"
    fi
    
    echo ""
}

# Quick invoice from deal
from_deal() {
    local project="$1"
    local client="$2"
    local deal_value="$3"
    
    if [[ -z "$project" || -z "$client" || -z "$deal_value" ]]; then
        error "Usage: from-deal <project> <client> <deal_value>"
        return 1
    fi
    
    echo "Generating invoice for closed deal..."
    echo ""
    echo "Project: $project"
    echo "Client: $client"
    echo "Amount: €$deal_value"
    echo ""
    
    generate_invoice "$project" "$client" "$deal_value" "Professional services" "$(date +%Y%m%d%H%M%S)"
}

# Main
case "${1:-help}" in
    generate)
        generate_invoice "$2" "$3" "$4" "$5" "$6"
        ;;
    paid)
        mark_paid "$2" "$3" "$4"
        ;;
    unpaid)
        list_unpaid
        ;;
    deal)
        from_deal "$2" "$3" "$4"
        ;;
    help)
        echo "Invoice Generator"
        echo ""
        echo "Usage: invoice_generator.sh <command> [args]"
        echo ""
        echo "Commands:"
        echo "  generate <proj> <client> <amt> [desc] [num]"
        echo "                            Generate new invoice"
        echo "  paid <project> <num> [date]  Mark invoice paid"
        echo "  unpaid                      List unpaid invoices"
        echo "  deal <proj> <client> <amt>  Quick invoice from deal"
        ;;
esac
