#!/bin/bash
# PHILOSOPHY KING — Twitter Post Generator
# Generates 3 philosophy posts, saves to queue for Jordan approval
# Run daily by cron

cd /data/workspace

TWITTER_QUEUE="PROJECTS/PK-MUSIC/twitter-queue.md"
TODAY=$(date '+%Y-%m-%d')

echo "=== PHILOSOPHY KING TWITTER === "
echo "Date: $TODAY"
echo ""

# Philosophy King tweets - intellectual, raw, global perspective
TWEETS="
---
Tweet 1 ($(date '+%Y-%m-%d')):
\"Memento Mori isn't about death.
It's about remembering you're alive enough to lose things.
Run towards the loss. That's where the life is.\"
#philosophy #MementoMori

---
Tweet 2 ($(date '+%Y-%m-%d')):
\"Ubuntu: I am because we are.
Capitalism: I am despite we are.
Pick your civilization.\"
#Ubuntu #philosophy

---
Tweet 3 ($(date '+%Y-%m-%d')):
\"The Stoics had it almost right.
Amor Fati is the move.
But you gotta choose what kind of death you're willing to die first.\"
#AmorFati #Stoicism
"

# Append to queue
if [ ! -f "$TWITTER_QUEUE" ]; then
    echo "# Philosophy King — Twitter Queue\n\n_Generated by Axton. Jordan approves. Then post._" > "$TWITTER_QUEUE"
fi

echo "=== NEW TWEETS ===" >> "$TWITTER_QUEUE"
echo "$TWEETS" >> "$TWITTER_QUEUE"
echo "" >> "$TWITTER_QUEUE"

echo "Tweets added to queue:"
echo "$TWEETS"

echo ""
echo "=== QUEUE LENGTH ==="
wc -l "$TWITTER_QUEUE"
echo "tweets in queue"

echo ""
echo "Done. Review $TWITTER_QUEUE and approve to post."
