#!/bin/bash
# Proposal Generator
# Create professional PDF-ready proposals

set -e

PROPOSALS_DIR="/data/workspace/PROJECTS"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[PROPOSAL]${NC} $1"; }
success() { echo -e "${GREEN}[PROPOSAL]${NC} $1"; }
error() { echo -e "${RED}[PROPOSAL]${NC} $1"; }

# Generate proposal
generate_proposal() {
    local project="$1"
    local client="$2"
    local scope="$3"
    local price="$4"
    local timeline="${5:-4 weeks}"
    
    if [[ -z "$project" || -z "$client" || -z "$scope" || -z "$price" ]]; then
        error "Usage: generate-proposal <project> <client> <scope> <price> [timeline]"
        return 1
    fi
    
    mkdir -p "$PROPOSALS_DIR/$project/proposals"
    
    local prop_num=$(date +%Y%m%d%H%M%S)
    local output_file="$PROPOSALS_DIR/$project/proposals/PROP-${prop_num}.md"
    local date=$(date +%Y-%m-%d)
    local valid_until=$(date -d "+14 days" +%Y-%m-%d)
    
    # Get project-specific content
    case "$project" in
        pisco)
            local company_name="PISCO"
            local service="Staff Placement Services"
            local description="Vetted Filipino professionals for your business needs"
            ;;
        comare)
            local company_name="COMARE"
            local service="Maintenance Services"
            local description="Professional pharmacy maintenance and support"
            ;;
        *)
            local company_name="${project^^}"
            local service="$project Services"
            local description="$scope"
            ;;
    esac
    
    cat > "$output_file" << EOF
# BUSINESS PROPOSAL

---

## $company_name — $service

**Proposal Date:** $date  
**Valid Until:** $valid_until  
**Proposal #:** PROP-$prop_num

---

## Prepared For

**$client**

---

## Executive Summary

$description

---

## Scope of Work

$scope

---

## Investment

| Service | Price |
|---------|-------|
| $service | €$price |
| | |
| **Total Investment** | **€$price** |

---

## Timeline

**Estimated Duration:** $timeline

| Phase | Deliverable | Week |
|-------|-------------|------|
| 1 | Discovery & Planning | 1 |
| 2 | Implementation | 2 |
| 3 | Review & Launch | 3-4 |

---

## Why $company_name?

- ✅ Proven track record
- ✅ Experienced professionals
- ✅ Dedicated support
- ✅ Quality guaranteed

---

## Next Steps

1. Review this proposal
2. Schedule a call to discuss
3. Sign the attached service agreement
4. Begin engagement

---

## Terms & Conditions

- Proposal valid for 14 days
- 50% deposit required to start
- Balance due upon completion
- Standard cancellation policy applies

---

*Ready to move forward?*  
Contact: [YOUR EMAIL]  
Phone: [YOUR PHONE]

---
*Generated by Jordan's Revenue System*
EOF
    
    success "Proposal generated: $output_file"
    echo ""
    echo "📄 Proposal created: $output_file"
    echo "👤 Client: $client"
    echo "💰 Investment: €$price"
    echo "📅 Valid until: $valid_until"
    echo ""
    
    # Log to proposal tracker
    log_proposal "$project" "$prop_num" "$client" "$price" "$date" "$valid_until"
    
    echo "$output_file"
}

# Log proposal
log_proposal() {
    local project="$1"
    local prop_num="$2"
    local client="$3"
    local price="$4"
    local date="$5"
    local valid="$6"
    
    local tracker="$PROPOSALS_DIR/$project/proposals/log.md"
    mkdir -p "$PROPOSALS_DIR/$project/proposals"
    
    if [[ ! -f "$tracker" ]]; then
        cat > "$tracker" << 'EOF'
# Proposal Log

| Proposal # | Client | Price | Sent | Valid Until | Viewed | Responded | Status |
|------------|--------|-------|------|-------------|--------|-----------|--------|
EOF
    fi
    
    cat >> "$tracker" << EOF
| PROP-$prop_num | $client | €$price | $date | $valid | NO | NO | SENT |
EOF
}

# Mark as viewed
mark_viewed() {
    local project="$1"
    local prop_num="$2"
    
    if [[ -z "$project" || -z "$prop_num" ]]; then
        error "Usage: mark-viewed <project> <proposal_num>"
        return 1
    fi
    
    local tracker="$PROPOSALS_DIR/$project/proposals/log.md"
    sed -i "s/| PROP-$prop_num |/| PROP-$prop_num */" "$tracker"
    sed -i 's/| NO |/| YES |/' "$tracker"
    success "Proposal PROP-$prop_num marked as VIEWED"
}

# Mark as responded
mark_responded() {
    local project="$1"
    local prop_num="$2"
    local response="${3:-INTERESTED}"
    
    if [[ -z "$project" || -z "$prop_num" ]]; then
        error "Usage: mark-responded <project> <proposal_num> [response]"
        return 1
    fi
    
    local tracker="$PROPOSALS_DIR/$project/proposals/log.md"
    sed -i "s/| PROP-$prop_num |/| PROP-$prop_num */" "$tracker"
    sed -i "s/| YES |/$response |/" "$tracker"
    success "Proposal PROP-$prop_num marked as: $response"
}

# List proposals
list_proposals() {
    local project="${1:-}"
    
    echo ""
    echo "═══════════════════════════════════════════"
    echo "  PROPOSAL TRACKER"
    echo "═══════════════════════════════════════════"
    echo ""
    
    if [[ -n "$project" ]]; then
        local tracker="$PROPOSALS_DIR/$project/proposals/log.md"
        if [[ -f "$tracker" ]]; then
            echo "📁 $project:"
            cat "$tracker"
        else
            echo "  No proposals for $project"
        fi
    else
        find "$PROPOSALS_DIR" -name "log.md" -exec grep -l "PROP-" {} \; 2>/dev/null | while read log; do
            local proj=$(echo "$log" | cut -d'/' -f6)
            echo "📁 $proj:"
            grep "PROP-" "$log" | head -5
            echo ""
        done
    fi
    
    echo ""
}

# Main
case "${1:-help}" in
    generate)
        generate_proposal "$2" "$3" "$4" "$5" "$6"
        ;;
    viewed)
        mark_viewed "$2" "$3"
        ;;
    responded)
        mark_responded "$2" "$3" "$4"
        ;;
    list)
        list_proposals "$2"
        ;;
    help)
        echo "Proposal Generator"
        echo ""
        echo "Usage: proposal_generator.sh <command> [args]"
        echo ""
        echo "Commands:"
        echo "  generate <proj> <client> <scope> <price> [timeline]"
        echo "                              Create new proposal"
        echo "  viewed <project> <num>      Mark proposal viewed"
        echo "  responded <project> <num> [status]  Mark responded"
        echo "  list [project]               List proposals"
        ;;
esac
