#!/bin/bash
# Agent Improvement System - Self-evolution for Axton
# Runs every Sunday, reviews the week, updates SOUL.md
# Run: ./self_improve_auto.sh

MEMORY_DIR="memory"
SOUL_FILE="SOUL.md"
LOG_SUCCESS="SUCCESS_LOG/weekly_improvement.log"
LOG_FAILURE="FAILURE_LOG/weekly_improvement.log"
WEEKLY_REVIEW="$MEMORY_DIR/weekly-review-$(date +%Y-W%V).md"

echo "=== Agent Improvement System ==="
echo "Running: $(date)"

mkdir -p "SUCCESS_LOG" "FAILURE_LOG"

# Collect week's data
collect_weekly_data() {
    echo "Collecting weekly metrics..."
    
    week_start=$(date -d '7 days ago' +%Y-%m-%d 2>/dev/null || date -v-7d +%Y-%m-%d)
    week_end=$(date +%Y-%m-%d)
    
    # Count memory entries this week
    week_entries=0
    for f in "$MEMORY_DIR"/[0-9][0-9][0-9][0-9]-*.md; do
        [ -f "$f" ] || continue
        file_date=$(basename "$f" | cut -d'-' -f1-3)
        if [[ "$file_date" >= "$week_start" ]] && [[ "$file_date" <= "$week_end" ]]; then
            ((week_entries++))
        fi
    done
    
    echo "Week entries: $week_entries"
}

# Analyze what worked
analyze_successes() {
    echo "Analyzing successes..."
    
    # Look for positive patterns
    successes=""
    
    # Check if content was generated
    if [ -f "PROJECTS/PK-MUSIC/content-queue.md" ]; then
        successes+="- Content pipeline executed successfully\n"
    fi
    
    # Check if second brain was queried
    if [ -f "PROJECTS/second-brain/second-brain.db" ]; then
        successes+="- Second brain system operational\n"
    fi
    
    # Check memory optimizer ran
    if grep -q "optimized" "SUCCESS_LOG/memory_optimizer.log" 2>/dev/null; then
        successes+="- Memory system maintained\n"
    fi
    
    echo -e "$successes"
}

# Analyze what didn't work
analyze_failures() {
    echo "Analyzing failures..."
    
    failures=""
    
    # Check failure logs
    for log in FAILURE_LOG/*.log; do
        [ -f "$log" ] || continue
        recent=$(find "$log" -mtime -7 2>/dev/null)
        if [ -n "$recent" ]; then
            failures+=$(basename "$log")
            failures+="\n"
        fi
    done
    
    # Check for stale tasks
    if [ -f "AUTONOMOUS.md" ]; then
        stale=$(grep -c "stale\|overdue" "AUTONOMOUS.md" 2>/dev/null || echo 0)
        if [ "$stale" -gt 0 ]; then
            failures+="- $stale stale tasks in queue\n"
        fi
    fi
    
    echo -e "$failures"
}

# Generate weekly review
generate_review() {
    echo "Generating weekly review..."
    
    cat > "$WEEKLY_REVIEW" << REVIEW
# Weekly Improvement Review
**Week of:** $(date -v-7d +%Y-%m-%d 2>/dev/null || date -v-7d +%Y-%m-%d) to $(date +%Y-%m-%d)

## Metrics
- Memory entries this week: $week_entries
- Tasks completed: $(grep -c "DONE\|completed" "$MEMORY_DIR"/*.md 2>/dev/null | awk -F: '{sum+=$2} END {print sum}' || echo 0)

## What Worked
$(analyze_successes)

## What Didn't Work
$(analyze_failures)

## Improvements to Make
1. 
2. 
3. 

## Notes for SOUL.md Update
- Be more [specific area]
- Less [unwanted behavior]
- More [desired behavior]

---
*Generated by Agent Improvement System*
REVIEW
    
    echo "Review saved: $WEEKLY_REVIEW"
}

# Update SOUL.md with improvements
update_soul() {
    echo "Updating SOUL.md..."
    
    # Read current SOUL.md
    if [ ! -f "$SOUL_FILE" ]; then
        echo "ERROR: SOUL.md not found"
        echo "$(date): FAILURE - SOUL.md not found" >> "$LOG_FAILURE"
        return 1
    fi
    
    # Create backup
    cp "$SOUL_FILE" "${SOUL_FILE}.backup.$(date +%Y%m%d)"
    
    # Add improvement section if doesn't exist
    if ! grep -q "## Recent Improvements" "$SOUL_FILE"; then
        echo "" >> "$SOUL_FILE"
        echo "## Recent Improvements" >> "$SOUL_FILE"
        echo "$(date +%Y-%m-%d): Initial improvement log" >> "$SOUL_FILE"
        echo "Added improvement section to SOUL.md"
    else
        # Append to existing section
        sed -i "\|## Recent Improvements|a\\$(date +%Y-%m-%d): Weekly review completed" "$SOUL_FILE" 2>/dev/null || \
        echo "$(date +%Y-%m-%d): Weekly review completed" >> "$SOUL_FILE"
    fi
    
    echo "SOUL.md updated"
}

# Log success
log_success() {
    echo "$(date): SUCCESS - Weekly improvement cycle completed" >> "$LOG_SUCCESS"
    echo "Logged to: $LOG_SUCCESS"
}

# Main execution
main() {
    if ! collect_weekly_data; then
        echo "$(date): FAILURE - Could not collect data" >> "$LOG_FAILURE"
        exit 1
    fi
    
    generate_review
    
    if ! update_soul; then
        exit 1
    fi
    
    log_success
    
    echo ""
    echo "=== Improvement Cycle Complete ==="
    echo "Review: $WEEKLY_REVIEW"
    echo "SOUL.md backup: ${SOUL_FILE}.backup.$(date +%Y%m%d)"
}

main "$@"
