#!/bin/bash
# weekly_review.sh — Runs every Sunday. Generates a weekly review memo.
# Usage: bash tools/weekly_review.sh

set -e

TODAY=$(date +%Y-%m-%d)
OUTPUT_DIR="memory"
OUTPUT_FILE="${OUTPUT_DIR}/weekly-review-${TODAY}.md"

# Ensure memory dir exists
mkdir -p "$OUTPUT_DIR"

# Load AUTONOMOUS for task context
AUTONOMOUS_CONTENT=""
if [ -f "AUTONOMOUS.md" ]; then
  AUTONOMOUS_CONTENT=$(cat AUTONOMOUS.md)
fi

# Load CRM for contact context
CRM_CONTENT=""
if [ -f "PROJECTS/personal-crm.md" ]; then
  CRM_CONTENT=$(cat PROJECTS/personal-crm.md)
fi

# Generate review
cat > "$OUTPUT_FILE" << 'REVIEW_EOF'
# Weekly Review — %TODAY%

> Jordan's weekly operating review. What completed, what slipped, what's next.

---

## ✅ What Completed This Week
- 
- 

## 🔴 What Slipped / Blocked
- 
- 

## 🔵 Current Priorities (from AUTONOMOUS)
(attach or inline relevant AUTONOMOUS items)

## 🧑‍🤝‍🧑 Relationship Check
- Anyone to follow up with?
- Birthdays coming up this week?

## 📊 Project Status

### PISCO
- 

### COMARE
- 

### Dealsmap
- 

## 💡 Lessons / Notes
- 
- 

## 🎯 Next Week's Top 3
1. 
2. 
3. 

---

_Review generated by Axton — weekly_review.sh_
REVIEW_EOF

# Replace placeholder with actual date
sed -i "s/%TODAY%/${TODAY}/g" "$OUTPUT_FILE"

echo "✅ Weekly review written to ${OUTPUT_FILE}"
echo ""
echo "📋 Review summary:"
echo "   - Completed: review file"
echo "   - Reminder: Jordan should fill in the blanks"
